name = "devcraft-agent-trigger"
main = "github-trigger.js"
compatibility_date = "2026-07-12"
account_id = "8f48a173bb73963b15a5231899f2e864"

[vars]
GITHUB_OWNER = "rutujdhodapkar"
GITHUB_REPO = "nvidia-verify"

[triggers]
crons = ["30 2 * * *", "30 6 * * *", "30 13 * * *", "30 4 * * *"]
